
INSERT INTO os_record_name(code, recname) values ('01','Acetate A4َ');
INSERT INTO os_record_name(code, recname) values ('02','Agrafeuse MMَ');
INSERT INTO os_record_name(code, recname) values ('03','Boite d''archive en cartonَ');
INSERT INTO os_record_name(code, recname) values ('04','Boite d''archive en plastiqueَ');
INSERT INTO os_record_name(code, recname) values ('05','Boite de tromboneَ');
INSERT INTO os_record_name(code, recname) values ('06','Chemise cartonnée glacéeَ');
INSERT INTO os_record_name(code, recname) values ('07','Classeurَ');
INSERT INTO os_record_name(code, recname) values ('08','Crayon noir HBَ');
INSERT INTO os_record_name(code, recname) values ('09','Effaceur styloَ');
INSERT INTO os_record_name(code, recname) values ('10','Encreَ');
INSERT INTO os_record_name(code, recname) values ('11','Enveloppe F10َ');
INSERT INTO os_record_name(code, recname) values ('12','Enveloppe F16َ');
INSERT INTO os_record_name(code, recname) values ('13','Enveloppe F24َ');
INSERT INTO os_record_name(code, recname) values ('14','Enveloppe F26َ');
INSERT INTO os_record_name(code, recname) values ('15','Markeur bleu-noir-rouge-vertَ');
INSERT INTO os_record_name(code, recname) values ('16','Papier listing GMَ');
INSERT INTO os_record_name(code, recname) values ('17','Papier listing PMَ');
INSERT INTO os_record_name(code, recname) values ('18','Papier listing PMَ');
INSERT INTO os_record_name(code, recname) values ('19','Ram de papier A3َ');
INSERT INTO os_record_name(code, recname) values ('20','Ram fiche bristol (21x29.7) blanche glacéeَ');
INSERT INTO os_record_name(code, recname) values ('21','Ram de papier Extra A4 80grsَ');
INSERT INTO os_record_name(code, recname) values ('22','Registre 2 mainsَ');
INSERT INTO os_record_name(code, recname) values ('23','Registre 3 mainsَ');
INSERT INTO os_record_name(code, recname) values ('24','Registre 4 mainsَ');
INSERT INTO os_record_name(code, recname) values ('25','Registre 5 mainsَ');
INSERT INTO os_record_name(code, recname) values ('26','Registre courrier arrivéeَ');
INSERT INTO os_record_name(code, recname) values ('27','Registre courrier départَ');
INSERT INTO os_record_name(code, recname) values ('28','Rouleau de faxَ');
INSERT INTO os_record_name(code, recname) values ('29','Rouleau de scotch d''emballage GMَ');
INSERT INTO os_record_name(code, recname) values ('30','Scotch MMَ');
INSERT INTO os_record_name(code, recname) values ('31','Sous chemiseَ');
INSERT INTO os_record_name(code, recname) values ('32','Stabilo bleu-noir-rouge-vertَ');
INSERT INTO os_record_name(code, recname) values ('33','Stylo bille bleu-noir-rouge-vert cello trio 1.0mmَ');
INSERT INTO os_record_name(code, recname) values ('34','CD-ROMَ');
INSERT INTO os_record_name(code, recname) values ('35','Clavier USBَ');
INSERT INTO os_record_name(code, recname) values ('36','DVD-ROMَ');
INSERT INTO os_record_name(code, recname) values ('37','Flash disk 16 GBَ');
INSERT INTO os_record_name(code, recname) values ('38','Flash disk 8 GBَ');
INSERT INTO os_record_name(code, recname) values ('39','Lingette de nettoyageَ');
INSERT INTO os_record_name(code, recname) values ('40','Multi prise TRUHTَ');
INSERT INTO os_record_name(code, recname) values ('41','Produit mousse de nettoyageَ');
INSERT INTO os_record_name(code, recname) values ('42','Ruban EPSON LQ 2070-2170-2080َ');
INSERT INTO os_record_name(code, recname) values ('43','Ruban EPSON LQ 2090-2190َ');
INSERT INTO os_record_name(code, recname) values ('44','Sourie USBَ');
INSERT INTO os_record_name(code, recname) values ('45','Toner brother DCP 9020َ');
INSERT INTO os_record_name(code, recname) values ('46','Toner LBP 6000َ');
INSERT INTO os_record_name(code, recname) values ('47','Toner LBP 3010َ');
INSERT INTO os_record_name(code, recname) values ('48','Toner LBP 2900َ');
INSERT INTO os_record_name(code, recname) values ('49','Toner K MITA 1635-1620َ');
INSERT INTO os_record_name(code, recname) values ('50','Toner K 1016َ');
INSERT INTO os_record_name(code, recname) values ('51','Toner K 1130َ');
INSERT INTO os_record_name(code, recname) values ('52','Sachet de poubelle GMَ');
INSERT INTO os_record_name(code, recname) values ('53','Eau de javel parfume 1Lَ');
INSERT INTO os_record_name(code, recname) values ('54','Top Sol 1Lَ');
INSERT INTO os_record_name(code, recname) values ('55','LAVE SOLَ');
INSERT INTO os_record_name(code, recname) values ('56','Savon liquide pour les mainsَ');
INSERT INTO os_record_name(code, recname) values ('57','serpillière 70x50 blache');
INSERT INTO os_record_name(code, recname) values ('58','L''Egan pour ménage');
INSERT INTO os_record_name(code, recname) values ('59','D''ésodorisant AIR well');
INSERT INTO os_record_name(code, recname) values ('60','Décapons');
INSERT INTO os_record_name(code, recname) values ('61','Anti calcaire 500ML');
INSERT INTO os_record_name(code, recname) values ('62','Ligette polish');
INSERT INTO os_record_name(code, recname) values ('63','Aigle en poudre 500G');
